-- Tabela: user
CREATE TABLE user_financial (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(200) NOT NULL,
    user_email VARCHAR(200) UNIQUE NOT NULL, 
    user_password_hash TEXT NOT NULL
);

-- Tabela: space
CREATE TABLE space_financial (
    space_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_name VARCHAR(200) NOT NULL, 
    space_description TEXT, 
    user_id INTEGER NOT NULL REFERENCES user_financial(user_id) ON DELETE CASCADE
);

-- Tabela: category
CREATE TABLE category_financial (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    category_name VARCHAR(200) NOT NULL,
    category_type VARCHAR(100) CHECK (category_type IN ('conta_fixa', 'cartao_credito', 'objetivo')) NOT NULL,
    space_id INTEGER NOT NULL REFERENCES space_financial(space_id) ON DELETE CASCADE
);

-- Tabela: transaction
CREATE TABLE transaction_financial (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_description TEXT,
    transaction_value NUMERIC(12,2) NOT NULL CHECK (transaction_value >= 0),
    transaction_date DATE NOT NULL,
    transaction_type VARCHAR(100) CHECK (transaction_type IN ('casa', 'lanche', 'transporte')) NOT NULL,
    category_id INTEGER NOT NULL REFERENCES category_financial(category_id) ON DELETE CASCADE,
    space_id INTEGER NOT NULL REFERENCES space_financial(space_id) ON DELETE CASCADE
);

-- Tabela: objective
CREATE TABLE objective_financial (
    objective_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objective_name VARCHAR(200) NOT NULL,
    objective_description TEXT,
    space_id INTEGER NOT NULL REFERENCES space_financial(space_id) ON DELETE CASCADE
);

-- Tabela: credit
CREATE TABLE credit_financial (
    credit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_name VARCHAR(200) NOT NULL,
    credit_limit NUMERIC(12,2) NOT NULL,
    credit_balance NUMERIC(12,2) NOT NULL,
    user_id INTEGER NOT NULL REFERENCES user_financial(user_id) ON DELETE CASCADE
);

-- Tabela: debt
CREATE TABLE debt_financial (
    debt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_name VARCHAR(200) NOT NULL,
    debt_total NUMERIC(12,2) NOT NULL,
    debt_paid NUMERIC(12,2) DEFAULT 0,
    debt_start_date DATE NOT NULL,
    debt_due_date DATE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES user_financial(user_id) ON DELETE CASCADE
);

-- Tabela: fixed_account
CREATE TABLE fixed_account_financial (
    fixed_account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixed_account_name VARCHAR(200) NOT NULL,
    fixed_account_value NUMERIC(12,2) NOT NULL,
    fixed_account_due_date DATE NOT NULL,
    user_id INTEGER NOT NULL REFERENCES user_financial(user_id) ON DELETE CASCADE
);

-- Tabela: compartilhamento_ambiente (futura)
CREATE TABLE sharing_space_financial (
    user_id INTEGER NOT NULL REFERENCES user_financial(user_id) ON DELETE CASCADE,
    space_id INTEGER NOT NULL REFERENCES space_financial(space_id) ON DELETE CASCADE,
    permission VARCHAR(10) CHECK (permission IN ('leitura', 'escrita')) NOT NULL,
    PRIMARY KEY (user_id, space_id)
);


SHOW client_encoding;
