-- Tabela: usuário
CREATE TABLE usuario (
    usuario_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_nome VARCHAR(200) NOT NULL,
    usuario_email VARCHAR(200) UNIQUE NOT NULL, 
    usuario_senha_hash VARCHAR(600) NOT NULL,
    usuario_ativo BOOLEAN DEFAULT TRUE, 
    usuario_dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela: ambiente  
CREATE TABLE ambiente (
    ambiente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente_nome VARCHAR(200) NOT NULL, 
    ambiente_descricao TEXT, 
    ambiente_dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE
);

-- Tabela: catergoria
CREATE TABLE categoria (
    categoria_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    categoria_nome VARCHAR(200) NOT NULL,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE
);

-- Tabela: transação
CREATE TABLE transacao (
    transacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transacao_descricao TEXT,
    transacao_valor NUMERIC(12,2) NOT NULL CHECK (transacao_valor >= 0),
    transacao_data DATE NOT NULL,
    transacao_ambiente_id INTEGER NOT NULL REFERENCES ambiente(ambiente_id) ON DELETE CASCADE,
    transacao_categoria_id INTEGER NOT NULL REFERENCES categoria(categoria_id) ON DELETE CASCADE,
    transacao_meta_id INTEGER REFERENCES meta(meta_id) ON DELETE SET NULL,
    transacao_local VARCHAR(200),
    transacao_observacao TEXT,
    transacao_recorrencia BOOLEAN DEFAULT FALSE,
    transacao_frequencia VARCHAR(50) CHECK (transacao_frequencia IN ('diaria', 'semanal', 'mensal', 'anual')),
    transacao_tipo_recorrencia VARCHAR(50) CHECK (transacao_tipo_recorrencia IN ('fixa', 'variavel')),
    transacao_dt_fim_recorrencia DATE,
    transacao_modo VARCHAR(50) NOT NULL CHECK (transacao_modo IN ('debito', 'credito', 'pix', 'dinheiro', 'TED', 'DOC', 'outros')),
    transacao_tipo VARCHAR(50) NOT NULL CHECK (transacao_tipo IN ('receita', 'despesa')),
    transacao_pago BOOLEAN DEFAULT TRUE,
    transacao_dt_pagamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    transacao_dt_vencimento DATE,
    transacao_total_parcelas INTEGER DEFAULT 1 CHECK (transacao_total_parcelas >= 1),
    transacao_parcela_atual INTEGER DEFAULT 1 CHECK (transacao_parcela_atual >= 1),
    conta_id INTEGER NOT NULL REFERENCES conta(conta_id) ON DELETE CASCADE   
);

-- Tabela: conta
CREATE TABLE conta (
    conta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_nome VARCHAR(200) NOT NULL,
    conta_tipo VARCHAR(50) NOT NULL CHECK (conta_tipo IN ('corrente', 'poupanca', 'investimento', 'cartao_credito', 'carteira', 'outros')),
    conta_saldo_limite_inicial NUMERIC(12,2) DEFAULT 0 CHECK (conta_saldo_limite_inicial >= 0),
    conta_saldo_limite_disponivel NUMERIC(12,2) DEFAULT 0 CHECK (conta_saldo_limite_disponivel >= 0),
    conta_dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    conta_ativo BOOLEAN DEFAULT TRUE,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE
);


-- Tabela: meta 
CREATE TABLE meta (
    meta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_nome VARCHAR(200) NOT NULL,
    meta_descricao TEXT,
    meta_valor_alvo NUMERIC(12,2) NOT NULL CHECK (meta_valor_alvo >= 0),
    meta_valor_atual NUMERIC(12,2) DEFAULT 0 CHECK (meta_valor_atual >= 0),
    meta_dt_limite DATE NOT NULL,
    meta_dt_inicial DATE NOT NULL,
    meta_concluida BOOLEAN DEFAULT FALSE,
    ambiente_id INTEGER NOT NULL REFERENCES ambiente(ambiente_id) ON DELETE CASCADE,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE
);

-- Tabela: compartilhamento ambiente
CREATE TABLE compartilhamento_ambiente (
    compartilhamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente_id INTEGER NOT NULL REFERENCES ambiente(ambiente_id) ON DELETE CASCADE,
    convidado_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE,
    permissao VARCHAR(50) NOT NULL CHECK (permissao IN ('leitura', 'escrita')),
    dt_convite TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    compartilhamento_status VARCHAR(50) DEFAULT 'pendente' CHECK (compartilhamento_status IN ('pendente', 'aceito', 'recusado')),
    UNIQUE (ambiente_id, usuario_id)
);

CREATE TABLE compartilhamento_meta (
    compartilhamento_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_id INTEGER NOT NULL REFERENCES meta(meta_id) ON DELETE CASCADE,
    convidado_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE,
    permissao VARCHAR(50) NOT NULL CHECK (permissao IN ('leitura', 'escrita')),
    dt_convite TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    compartilhamento_status VARCHAR(50) DEFAULT 'pendente' CHECK (compartilhamento_status IN ('pendente', 'aceito', 'recusado')),
    UNIQUE (meta_id, usuario_id)
);

CREATE TABLE perfil (
    perfil_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE
    perfil_tipo VARCHAR(50) NOT NULL CHECK (perfil_tipo IN ('Gastador', 'Poupador', 'Controlado', 'ETC', 'outros')),
    perfil_descricao TEXT,
    perfil_dt_calculo TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feedback_financeiro(
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE,
    feedback_tipo VARCHAR(50) NOT NULL CHECK (feedback_tipo IN ('sugestao', 'reclamacao', 'elogio', 'outros')),
    feedback_mensagem TEXT NOT NULL,
    feedback_dt_geracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE relatorio_financeiro (
    relatorio_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relatorio_tipo VARCHAR(50) NOT NULL CHECK (relatorio_tipo IN ('mensal', 'anual', 'personalizado')),
    relatorio_formato VARCHAR(50) NOT NULL CHECK (relatorio_formato IN ('pdf','csv')),
    relatorio_dt_geracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE,
    relatorio_caminho_arquivo TEXT NOT NULL
);

CREATE TABLE extrato_pdf (
    extrato_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extrato_nome_arquivo TEXT NOT NULL,
    extrato_dt_importacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id INTEGER NOT NULL REFERENCES usuario(usuario_id) ON DELETE CASCADE,
    extrato_processamento_status VARCHAR(50) DEFAULT 'pendente' CHECK (extrato_processamento_status IN ('pendente', 'processando', 'concluido', 'erro')),
    UNIQUE (usuario_id, extrato_nome_arquivo)
);

SHOW client_encoding;
